### ISSUE TITLE
Right click translation window too small

### ISSUE THREAD

**Issue by DannyWho** [Lusito/dict.cc-translation#16]
Hey,

suddenly, when I ALT-Click words for the micro-window, this window is too small to show content and a scroll bar is overlaying the text. Reinstalling, rebooting the addon and updating Firefox didn’t help.

I am on Mac OS 10.9.5 and Firefox 45 and 46.

**Comment by Lusito** [comment]
Thanks for the report. Sadly I can't seem to reproduce it (don't have a mac available)
Maybe it's possible to figure it out differently:
- Did the Problem occur with version 4.0 or with 4.1?
- Does it happen on any page or just in some situations?
- Does it happen for the popup overlay panels as well? (full or pocket)
- Can you make a screenshot?

**Comment by Lusito** [comment]
I've created a beta version 4.1.1b2 to disable the scrollbars alltogether:
https://addons.mozilla.org/de/firefox/addon/dictcc-translation/versions/beta
Please try this and make a screenshot so I can check if there are any visual issues this may cause.

**Comment by DannyWho** [comment]
Without trying the things above, the beta works fine again. And there is a German localisation now :)

**Comment by Lusito** [comment]
Even if it works fine, could you please make a screenshot? I'd like to see if there any visual differences on mac. Thanks

**Comment by DannyWho** [comment]
![bildschirmfoto 2016-05-08 um 12 01 52](https://cloud.githubusercontent.com/assets/19171171/15097218/bab1c4ae-1514-11e6-88d1-9b3297598eb1.png)

this is what the quick click with the smallest overlay looks like now in the beta.

this is the pocket version:
![bildschirmfoto 2016-05-08 um 12 04 02](https://cloud.githubusercontent.com/assets/19171171/15097235/18201e9c-1515-11e6-8e79-07e78b2fff6d.png)

this is the fully detailed popup:
![bildschirmfoto 2016-05-08 um 12 04 30](https://cloud.githubusercontent.com/assets/19171171/15097238/221fb556-1515-11e6-8802-4ee9da6d2ea5.png)

**Comment by Lusito** [comment]
I see, that explains why you got scroll-bars:
It seems there is an additional border around your panel, so I need to increase the size by 2 px for mac.
Thanks.
