### ISSUE TITLE
Popup (all details) (4.x)

### ISSUE THREAD

**Issue by aleckscastro** [Lusito/dict.cc-translation#17]
The new "Popup (all details)" window in Dict.cc Translation 4.x is now a modal window, what seems to be an integration with Firefox' Australis UI. 

In this new version, it's no longer possible to move the popup window or set it to "Always On Top" on Linux, which was useful while reading and translating text. Clicking outside the popup, or switching between tabs or apps cause the popup to close. Is it possible to make "Popup (all details)" an actual Firefox popup window again and not a modal window?

Version: 4.2.0
![screenshot from 2016-05-19 09-39-13](https://cloud.githubusercontent.com/assets/953072/15386211/c7010482-1da6-11e6-83fb-39772b63b632.png)

**Comment by Lusito** [comment]
There is an option to use a classic popup. With a single checkbox click it should behave exactly as before. If not, please create a bug-report.

**Comment by aleckscastro** [comment]
Unchecked "Use an overlay panel instead of a popup." Works. Thank you!
