### ISSUE TITLE
find inflected forms

### ISSUE THREAD

**Issue by danielnaber** [Lusito/dict.cc-translation#18]
I know this is a limitation of dict.cc itself, but maybe we can find a solution anyway: most inflected forms are not found, e.g. `nadas` (Spanish, 2nd person singular of `nadar`). I see two possible solutions:
- Convince dict.cc to support inflected forms
- Look up the base form in the add-on

The data (fullform -> base form) is already available in a highly compressed binary format, e.g. [here](https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/es/src/main/resources/org/languagetool/resource/es/spanish.dict) for Spanish (450KB). It can be read by [morfologik](https://github.com/morfologik/morfologik-stemming/), but that's a Java-based software. It might be possible to port it to Javascript or to find some other way to compress the data. The Spanish data (~670K word forms) is 20MB as uncompressed plain text and 3MB when zipped.

**Comment by SebastianZ** [comment]
While I would also like to have a feature like this, I believe this should not be part of this extension. Reasons:

- This feature is not part of dict.cc (and Dict.cc Translation only targets features offered on dict.cc)
- It increases the size of the extension a lot (especially when more than one language is covered; even when you don't use that specific language)

So, I think this should rather be supported by dict.cc itself. Though from my experience feature requests are blocked by Paul Hemetsberger.

Sebastian

**Comment by Lusito** [comment]
Thanks for the report.
I've contacted Paul Hemetsberger about this (the owner of dict.cc).
I'm not gonna add actual translation code into the add-on.

**Comment by Lusito** [comment]
Paul said he likes the idea and will take a more detailed look at it once he has time for new features.

**Comment by SebastianZ** [comment]
> Paul said he likes the idea and will take a more detailed look at it once he has time for new features.

Sounds good. Thank you for contacting Paul about that!

Sebastian

**Comment by Lusito** [comment]
Closing this issue for now, as it's to be solved by dict.cc itself and not the add-on.
