### ISSUE TITLE
Default translation for Quick translation

### ISSUE THREAD

**Issue by stonerl** [Lusito/dict.cc-translation#21]
Would it be possible to set a default translation for "Quick Translation"? For example the first entry from the translation list.

**Comment by Lusito** [comment]
Unless I don't get your issue, it already is like that and It has been for ages.
Quick left => first entry in the translation list
Quick right => a context menu appears

**Comment by stonerl** [comment]
Sorry, it was just me being stupid. I had to change the key combination. On a Mac ctrl is used for right clicks. So I was always doing a right click.

**Comment by Lusito** [comment]
No Problem
