### ISSUE TITLE
Porting the add-on to Web-Extensions

### ISSUE THREAD

**Issue by Lusito** [Lusito/dict.cc-translation#24]
Sadly, Mozilla is going to block all non-web-extension add-ons in nov. 2017. So a port is not avoidable.
See my rant about it here: https://github.com/Lusito/dict.cc-translation/wiki/Rant-about-Mozilla

I've submitted a web-extension version (5.0a) on the beta-channel:
https://addons.mozilla.org/en/firefox/addon/dictcc-translation/versions/beta?page=1#version-5.0a

@aleckscastro, @DannyWho, @SebastianZ, @Filbuntu, @danielnaber, @scrapix, @stonerl
I'm inviting you all to try this new version.

**Comment by Filbuntu** [comment]
Thanks a lot for working on this, although the cause is not a happy
one!
I could install the new version but it seems not to probably work with
my Firefox 51.0.1 (Ubuntu Linux) yet. The preferences look like this:
I don't get a right-click-mouse-options and the ctrl-mouse-click does
not work , either. Maybe as this is an early version, these feature
don't work yet anyway.
The address bar pop-up field opens but no language can be chosen and if
I type in a word (with enter) nothing happens.

Thanks again for your work on this! Much appreciated.

**Comment by Lusito** [comment]
Thanks for the feedback.. all features should be implemented.
On my windows Firefox 50.1 they all work. I'll try upgrading and also I'll try using my xubuntu firefox.
Have you tried restarting firefox?

>The preferences look like this:
Is a screenshot missing here?

**Comment by Filbuntu** [comment]
Yes, the screenshot did not make it from the html-email sent to the
list but I am manually inserted it, hopefully you can view it.

I wondered whether another add-on (or setting) causes some troubles and
unfortunately this may be the problem. In the same Firefox-version
(without add-ons and other changes) the new dict.cc-add-on works. 
I don't have much time now to find out which of the many add-ons or
settings causes the problem, though, as I am in the midst a busy time
(till end of March), sorry about that.
But in the default Firefox the add-on seems to work although I could
not make happen the quick-link-translation.

Yes, I have also restarted Firefox.

Thanks again for your hard work on this!

**Comment by Lusito** [comment]
I've tried it with Firefox 51.0.1 on both windows and xubuntu, and except from a few small bugs it works:
- rocker gesture does not seem to work correctly from right to left.. only left to right works correctly
- micro-panel size does not get calculated correctly.

Could you give me the list of add-ons you have installed? Then I could try to reproduce it.
Thanks so far.

**Comment by Lusito** [comment]
The screenshot looks like some sort of issue with the internationalization. There are translations for "de" and "en", but fallback should be "en".

**Comment by Filbuntu** [comment]
> The screenshot looks like some sort of issue with the
> internationalization. There are translations for "de" and "en", but
> fallback should be "en".

Where would I change this?

**Comment by Lusito** [comment]
Not from my add-on. It's the browsers language you have configured.

**Comment by Lusito** [comment]
I guess it must be something different.. since a lot of the functionality doesn't seem to work, something probably stops my code from being executed, which may also be the cause of the untranslated options.
I can't imagine other add-ons causing this kind of behavior, since web-extensions should not interact with other add-ons except via a special messaging api, which would need my add-on id.

So my best guess is, that it's some kind of setting. 
Could you try the following:
- enter "about:debugging" in the url field.
- check "enable add-on debugging".
- to the right of dict.cc, click on "debug" and accept the connection.
- switch to the console tab
- click on the dict.cc address bar pop-up button
- if by clicking on it, some error message appears in the console window, copy it and paste it here.
- if nothing new appeared, please copy the entire content (select all via context menu works best).
- after that, you can close the debugger window and disable add-on debugging again.

Thank you.

**Comment by Filbuntu** [comment]
> Not from my add-on. It's the browsers language you have configured.

After a second search in the Firefox configuration, I found a language
setting option (Content/Languages) but it only showed en-us and en. I
deleted en-us and then restarted Firefox. This did not work. I searched
about:config for languages and reset some very old settings for
firegloves and globefish (I could not delete the entry). Another
restart of Firefox and nothing changed unfortunately.
If you any other tips regarding the browser language, I am happy to
try.

**Comment by Filbuntu** [comment]
Debugging:
Upon "click on the dict.cc address bar pop-up button" twice:

The character encoding of the HTML document was not declared. The
document will render with garbled text in some browser configurations
if the document contains characters from outside the US-ASCII range.
The character encoding of the page must be declared in the document or
in the transfer protocol.  popup.html
XrayWrapper denied access to property Symbol.toPrimitive (reason:
object is not safely Xrayable). See https://developer.mozilla.org/en-US
/docs/Xray_vision for more information. Note that only the first denied
property access from a given global object will be
reported.  script.js:2354:4
The character encoding of the HTML document was not declared. The
document will render with garbled text in some browser configurations
if the document contains characters from outside the US-ASCII range.
The character encoding of the page must be declared in the document or
in the transfer protocol. popup.html
Use of getPreventDefault() is deprecated.  Use defaultPrevented
instead.  popup.html

The whole debugging report (with css, only js):
Unchecked lastError value: Error: Could not establish connection.
Receiving end does not exist.  ExtensionUtils.jsm:381
	withLastError resource://gre/modules/ExtensionUtils.jsm:381:9
	wrapPromise/< resource://gre/modules/ExtensionUtils.jsm:432:11
	onRejected self-hosted
	onRejected self-hosted
Use of getPreventDefault() is deprecated.  Use defaultPrevented
instead.  addons
Use of getPreventDefault() is deprecated.  Use defaultPrevented
instead.  debugging
The character encoding of the HTML document was not declared. The
document will render with garbled text in some browser configurations
if the document contains characters from outside the US-ASCII range.
The character encoding of the page must be declared in the document or
in the transfer protocol.  popup.html
XrayWrapper denied access to property Symbol.toPrimitive (reason:
object is not safely Xrayable). See https://developer.mozilla.org/en-US
/docs/Xray_vision for more information. Note that only the first denied
property access from a given global object will be
reported.  script.js:2354:4
The character encoding of the HTML document was not declared. The
document will render with garbled text in some browser configurations
if the document contains characters from outside the US-ASCII range.
The character encoding of the page must be declared in the document or
in the transfer protocol.  popup.html
Use of getPreventDefault() is deprecated.  Use defaultPrevented
instead.  popup.html

**Comment by Lusito** [comment]
Thanks, sadly nothing out of the ordinary tho..
Thats one reason why I hate firefox.. some errors seem to be swallowed without any notification.

Since you don't have time right now, I'd say we wait a couple of firefox versions (57 is the version which will break compatibility). Hopefully they will have sorted some things out until then.

**Comment by Filbuntu** [comment]
Thanks you, too! Maybe somebody else has the same problem and will be
able to contribute.

**Comment by SebastianZ** [comment]
I still need to try out the new version, though regarding your rant, Mozilla is trying to recreate a few APIs for WebExtensions. E.g. a sidebar API was created a few days ago in [bug 1208596](https://bugzilla.mozilla.org/show_bug.cgi?id=1208596) (didn't try it out myself yet, though).

Sebastian

**Comment by Lusito** [comment]
Yes, I've seen the plan for the sidebar, but at least when I read about it, it was a 'you need to click a button to show it' thing just like the popup overlay, so no showing it programmatically. And that kind of crippling is planned for all APIs that would be interesting to me.

**Comment by CennoxX** [comment]
Thanks for porting the add-on! It works overall great in FF 53.
Just some minor things:

- Clicking "Save" does not give any visual feedback, initially this was very irritating, I thought the settings didn't saved.
- My interface is localized (in German), but the languages ​​are still displayed in English.
- In "Options"> "Translation List"> "Add new entry" in "Second Language" appear sometimes duplicate entries for "English" and "German" – for example, if I click on "Clear list" and "Save". After a click on "Refresh" these duplicate entries disappear.
- When using the micropanel, the background is greyed out, which is very irritating / interrupts the workflow.
- If "Quick Translation" is clicked you still have to move the cursor in the input field, is it possible to do this automatic? Also, can you can load the result instant (perhaps after X ms)?

It's a pity that "Show first translation at top level" is not possible (even if you do not use the "Options" at that place?)

Greets

**Comment by Lusito** [comment]
>Clicking "Save" does not give any visual feedback

yes, I've noticed that as well and fixed it two weeks ago.. I just haven't uploaded a new version yet, as it seemed minor.
On Chrome, the settings are a popup window which closes on save, which is more in harmony with the save/cancel buttons. Firefox does this a bit differently.

>My interface is localized (in German), but the languages ​​are still displayed in English.

Yes, well the languages I grab directly from dict.cc, which serves it in english. Not much I can do about it except keep a list of all languages in the world (in case dict.cc adds them at some point) and translate them manually. I think users will be able to figure this one out.

>sometimes duplicate entries for "English" and "German"

That's weird, I'll try to reproduce this.

>When using the micropanel, the background is greyed out

The reason why I did it is the following: Before, micropanel was a popup from firefox, which was completely without problems. But now I need to put it as html into the website and add a layer over everything so that I can catch clicks correctly to destroy the micropanel when someone clicks outside of it.
I've made it a transparent gray so the user can see that something is in the way, so he knows why a click on the website didn't do anything.
Of course I can make it invisible, but I thought it would help users understand the clicking issue.

>If "Quick Translation" is clicked you still have to move the cursor in the input field

This should already be focused automatically. Not sure why it doesn't for you. I'll see what I can do.

>Also, can you can load the result instant (perhaps after X ms)?

What do you mean? does it take too long to translate? I can't change that, since it is a web request to dict.cc. I don't do any translation in the add-on without a request to dict.cc.
If it takes too long to show anything, I could show a "loading" icon.

>It's a pity that "Show first translation at top level" is not possible (even if you do not show the other translations and "Options" at that place?)

It would be possible to only show the "first translation at top level" with all the other entries disabled. It would require some rewriting tho, so it will come back at a later version.

**Comment by Lusito** [comment]
>If "Quick Translation" is clicked you still have to move the cursor in the input field

Ok, I guess I only tested the focus issue on Chrome. Firefox seems to have an issue with this and there is already a bugreport for it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1338909

I'll see if the mentioned workaround works here as well.

**Comment by CennoxX** [comment]
Thanks for your quick answers.
> What do you mean? does it take too long to translate?
I meant an instant search like in Google Instant, without clicking the enter key, if I didn't enter something for some time.
I don't know tho if that is worth the effort. It was just a lot of clicking to get to the translation...

**Comment by Lusito** [comment]
Well, that would be possible, but since dict.cc is not a huge company like google, I don't want to strain their bandwidth too much if possible. Pressing the Enter key is something that you can do right after typing without letting go of the keyboard, so I think it's acceptable.

Maybe when Paul creates a REST API, so the requests aren't as big as they are right now (I'm basically downloading the pocket.dict.cc website html).

**Comment by Lusito** [comment]
dict.cc seems to have some kind of autosuggest, but the results are a bit limited.. if you think it's useful enough, I could make it optionally available to show this kind of dropdown while typing, but the user would still have to press enter to select one of these results.

**Comment by Lusito** [comment]
A new version has been released on the development channel.
https://addons.mozilla.org/en-US/firefox/addon/dictcc-translation/versions/beta

**Comment by bitstreamout** [comment]
Success here using micro panels and  configured Ctrl+Button1 with DE<>EN

**Comment by Lusito** [comment]
A new version has been released on the development channel.
https://addons.mozilla.org/en-US/firefox/addon/dictcc-translation/versions/beta

Same Version is on the way through Mozilla to be officially released as stable.
It's on queue position 206, so it might take a while.
If you find any bugs, report them before it's through the queue.
