### ISSUE TITLE
No switch back to previous tab when closing the dict.cc tab.

### ISSUE THREAD

**Issue by Atalanttore** [Lusito/dict.cc-translation#29]
Hi,

the Dict.cc Translation Web-Extension can open a new tab for displaying dict.cc results, but it doesn't switch back to the previous tab when closing the dict.cc tab.

Regards,
Ettore

**Comment by Lusito** [comment]
Hi, that is some weird behavior by Firefox. I will see if I can do anything about it when I have a bit more time.

**Comment by Lusito** [comment]
This is a feature that will be available with Firefox 57 and the next version of the add-on.
I've added the code with a version check, so once Firefox 57 rolls out, it should work (Tested with Firefox nightly 58)

**Comment by Atalanttore** [comment]
Thanks!
