### ISSUE TITLE
Micropanel wrong translation

### ISSUE THREAD

**Issue by pank** [Lusito/dict.cc-translation#30]
Hi,

Thanks for developing this addon.  It's very useful and dict.cc is nice.

I was reading [this](https://www.tagesschau.de/ausland/trump-besuch-polen-101.html) article.  It features the word "Flüssiggas" just under the main picture.  When I look up the definition using micropanel it suggests:

> schick, cool, sexy, more

when I click *more* the correct translation is shown in a pop-up.

When I look up the word using the addon translation icon, it the following, which looks more correct.

> Flüssiggas {n}
>    liquid gas
>    liquefied petroleum gas <LPG>
>    liquified petroleum gas <LPG> [spv.]
> Flüssiggas-Tanker {m} [auch: Flüssiggastanker]
>    liquefied petroleum gas tanker <LPG tanker>

I'm on a GNU/Linux system and I'm using Firefox 54.  The addon version 5.1.

Thanks,
Rasmus

**Comment by Lusito** [comment]
Thanks for reporting it. It's not an issue of my add-on tho:
http://www.dict.cc/dcc-gadget.php?s=Fl%C3%BCssiggas
I will forward this issue to Paul, the author of dict.cc

**Comment by pank** [comment]
You are right.  Thanks.

**Comment by Lusito** [comment]
Paul fixed the issue.
