### ISSUE TITLE
Translation option on context menu (main pane) is missing

### ISSUE THREAD

**Issue by Farbauti** [Lusito/dict.cc-translation#31]
After setting up a new computer (Win10, with FF and all) I cannot manage to get the direct translation entry in the context menu.
For clarification I refer to the screenshot of https://addons.mozilla.org/en-US/firefox/addon/dictcc-translation

![screenclip](https://user-images.githubusercontent.com/31306453/29657536-3d1155a0-88b8-11e7-9e71-ea849227f460.png)

This is what my last computer installation looked like.
The new installation only features the "tranlate XXX >" sub menu.

**Comment by CennoxX** [comment]
This is due to the porting to web-extentions (https://github.com/Lusito/dict.cc-translation/issues/24), because Firefox will discontinue all add-ons except web-extensions. Some feature have been lost completely because of that, see https://github.com/Lusito/dict.cc-translation/wiki/Rant-about-Mozilla:
> - I can't freely customize the context-menu items. It is possible to create multiple entries, but as soon as there is more than one item, they will be moved in a submenu named after the add-on.
> 
>   -   So gone is the option "Show first translation at top level"
>

**Comment by steelbath** [comment]
I highly back up this concern. It's the only way i used the add on and it's far nicer if you don't have a hand on the keyboard and don't need to go into a submenu every time.

so if there is a way to implement an option for that to get it back i would highly appreciate it too.

**Comment by Lusito** [comment]
Will be fixed in the next version
