### ISSUE TITLE
Middle clicking 'more...' to open in new tab

### ISSUE THREAD

**Issue by jnachtigall** [Lusito/dict.cc-translation#33]
Using the firefox extension. Would be cool if one could middle-click on the `more...` link to open the further results in a new tab instead of in a new window:

![image](https://user-images.githubusercontent.com/3307404/35391734-d40878b2-01df-11e8-8934-016d4a37976c.png)

I am used to having open multiple tabs but hate to have multiple windows/popups.

Also, for users of vertical tabs (in the sidebar not at topbar), the default popup-size does not work:
![image](https://user-images.githubusercontent.com/3307404/35391927-6d11edae-01e0-11e8-9657-637b2be43a02.png)

This would be fixed as well by making the `more` link a normal `<a href="" target="_blank">`

Besides this, thanks for the nice extension, loving it ❤️

**Comment by Lusito** [comment]
Thanks. This is indeed a valid request.

**Comment by Lusito** [comment]
Will be fixed in the next version. I'll wait a couple of days before releasing it to see if I can add a couple of more changes.
