### ISSUE TITLE
Translate word under cursor instantly when the gesture is used

### ISSUE THREAD

**Issue by ei-ke** [Lusito/dict.cc-translation#35]
Hello Lusito,
first let me thank you for creating this addon.
I think it would be awesome to instantly translate word when only one language is set up (in my case DE<>EN) when using the "Wippgeste" (pressing the left and then the right mouse button for those who don't speak German) instead of having to select the language in the microwindow created upon this gesture.
Not a bit issue, but I'm spoiled from the Chrome addon I used were I only needed to select the word and done.

Greetings
Eike

**Comment by Lusito** [comment]
Hello Eike,

the Wippgeste (english rocker gesture) depends on the direction you rock. I.e. if you first press left, then right, it will show a context menu, but if you first press right, then left, it will instantly translate.

Hope this helps :-)
Greetings

**Comment by ei-ke** [comment]
Strange. left -> right is not working for me, but this does the trick:
left -> right -> hold right -> left...
Firefox 60.0rc2-1 @ Arch Linux

**Comment by ei-ke** [comment]
If there are some tests I can perfoem just let me know and I'm glad to help you.
