### ISSUE TITLE
Reader View

### ISSUE THREAD

**Issue by Taranis01** [Lusito/dict.cc-translation#36]
Hey, thanks for this very helpful addon :-)

i am reading many english texts with the reader view mode and would like to use dict.cc there too. Can you activate the addon for reader view too?

**Comment by Lusito** [comment]
Hi Taranis,

I'm glad you like it. Sadly, there is currently no way to add content scripts to the reader view, so no quick click can be used.

You can however still select the text manually and open the context menu to translate. It's a few more clicks, but it gets the job done.

There is a ticket addressing the missing access to reader view, but It seems they won't do anything about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1286387

Hope this helps.

**Comment by Taranis01** [comment]
Ok there is no way then. However translating via context menu is not possible too because, while other plugins are in the context menu, dict.cc Translation isn't.

**Comment by Lusito** [comment]
If it's not available in normal viewing mode either, then you probably have it disabled in the settings. 
Otherwise it would be a bug. For me it works.
