### ISSUE TITLE
Shift key problematic for quick context menu.

### ISSUE THREAD

**Issue by Lusito** [Lusito/dict.cc-translation#4]
When pressing Shift, Firefox does not allow disabling the context menu.
So Quick context menu with shift is problematic.
This is actually not a bug, but a feature as specified here:
https://html.spec.whatwg.org/multipage/forms.html#context-menus

I'm not sure if it is possible to disable or hide the context menu using SDK access.
Need to do some research and if nothing is found, at least warn the user about this problem.

**Comment by SebastianZ** [comment]
This problem obviously got solved with https://github.com/Lusito/dict.cc-translation/commit/b21652af489bd02f7d5b56f827ae55d3dc12fd14.

Sebastian

**Comment by Lusito** [comment]
I don't think so..

**Comment by SebastianZ** [comment]
Oops, wrong commit, I meant https://github.com/Lusito/dict.cc-translation/commit/a26ea05d99c7ddacb4a3431b7b169605f3de23dd.

Sebastian

**Comment by Lusito** [comment]
Well, not for me in Firefox nightly.

**Comment by SebastianZ** [comment]
Oh, right. It's working in Stable, though failing in Nightly, probably due to e10s again. :disappointed: 

Sebastian

**Comment by Lusito** [comment]
actually it's not. As said above, it's actually a feature mozilla chose to implement.

**Comment by Lusito** [comment]
closing this issue for now, added a warning.
