### ISSUE TITLE
Improvement when opening a popup from a micropanel on FF (OSX)

### ISSUE THREAD

**Issue by poohsen** [Lusito/dict.cc-translation#40]
I'm on OSX Mojave, running the latest FF. When I open a translation in a micropanel and then click on 'more', that takes me to a pocket version popup. This works fine but when you go back to the page you're reading again, the popup disappears into the background. If you again open a mircopanel and click more, your translation will be loaded into the popup but the popup window won't be moved into the foreground.

Not sure if the current FF API provides a way to do the but it would be great if the popup could be moved into the foreground in the case that it already exists. The workaround is to remember to close it every time or to cycle windows until it's shown again. Not too terrible but not ideal.

**Comment by Lusito** [comment]
Sorry, this went below my radar. I will look into it.

**Comment by Lusito** [comment]
Will be fixed in the next version
