### ISSUE TITLE
dict.cc addon doesn't work in PDF.js

### ISSUE THREAD

**Issue by Atalanttore** [Lusito/dict.cc-translation#44]
Hi,

The dict.cc translation addon doesn't work within Firefox's inbuilt PDF viewer PDF.js

**Comment by Lusito** [comment]
Hi,

the inbuilt PDF viewer doesn't allow for the minilayer or the quick click actions, but you can still select text and use the context menu.
I'm afraid there isn't anything I can do to improve the situation. If the context menu doesn't work for you either, please let me know (it works for me).
