### ISSUE TITLE
Pop up box is black

### ISSUE THREAD

**Issue by lgommans** [Lusito/dict.cc-translation#47]
For me, the box looks like this these days:

![](https://i.snag.gy/MBJL9Y.jpg)

By selecting the text (which is difficult given that most of it is a link and I use Alt+drag as a global window movement modifier on Linux), I can manage to read it:

![](https://i.snag.gy/oXe2kw.jpg)

Looking in the element inspector, the link text is set to black, but I see no background being applied to the container. Maybe that should be set to white instead of leaving it up to some default that I might have changed (I'm not sure if I changed any such setting in my browser)?

**Comment by Lusito** [comment]
The body element has a background color, which is the gray color you see around the black one. The black element in your screenshot should have the background color of the body element. Not sure why it shows as black, but I've seen similar rendering issues with the toolbar popup in older versions of Firefox.

What Firefox version are you using? Also, are you possibly using a dark theme for your operating system?

**Comment by lgommans** [comment]
I use the latest stable Firefox (currently 68.0.1). Any setting I can set to dark, is set to dark. I don't think I have an OS setting that is dark, but I may misremember. My Firefox theme is dark.

**Comment by Lusito** [comment]
Almost two years later, I finally added a dark mode. Sorry about the delay.
