### ISSUE TITLE
Alt key without any other modifier problematic for quick key in e10s

### ISSUE THREAD

**Issue by Lusito** [Lusito/dict.cc-translation#5]
When using multi-process mode of firefox (e10s), using the Alt key as the only modifier is problematic:
The application menu will show up and hide any panel. Tabs work, but the menu is still open, which is still too ugly.
Using any other modifier in combination with alt stops this bug.

It should be possible to disable this by intercepting the keypress event from the pagemod.js file.
This should of course only happen if a translation has actually occured.

**Comment by Lusito** [comment]
update: intercepting keypress,keyup, keydown does nothing at all. That makes it a lot harder to fix

**Comment by SebastianZ** [comment]
In case this can't be fixed, I'd suggest to add a warning when only the *Alt* checkbox is checked within the settings and to [file a platform bug](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=DOM%3A%20Events) for that.

Sebastian

**Comment by Lusito** [comment]
closing this issue for now, added a warning.
