### ISSUE TITLE
[BUG] Different word order between views

### ISSUE THREAD

**Issue by TobiasSekan** [Lusito/dict.cc-translation#51]
Hello,

I have notice that the ordering in the word listing between the views is sometimes different.
It wold be nice when the ordering of word listing where the same in the different views.

best wishes

# Micro panel

![2020-09-04 07_46_23-Merge pull request #47398 from CyrusNajmabadi_nonRequired · dotnet_roslyn@412f9a](https://user-images.githubusercontent.com/17874713/92204287-6f151300-ee83-11ea-9730-75436f23b499.png)

# PopUp window/tab

![2020-09-04 07_46_40-pocket dict cc _ Mobile Dictionary](https://user-images.githubusercontent.com/17874713/92204288-70ded680-ee83-11ea-96ac-f1785bc0de1f.png)

# My environment
* Windows 10 Version 2004
* Firefox 81.0b5
* Dict.cc Translation extension 5.3.2

**Comment by CennoxX** [comment]
The different order comes from the pocket view of dict.cc (pocket.dict.cc), not from the addon. So I don't think it's a bug on the addons end.

**Comment by Lusito** [comment]
@CennoxX is correct. You'd have to direct this request to Paul Hemetsberger, see dict.cc: https://www.dict.cc/?s=about%3A&l=e
