### ISSUE TITLE
"Rechtsklick für mehr Optionen aktivieren" ohne Funktion

### ISSUE THREAD

**Issue by CennoxX** [Lusito/dict.cc-translation#53]
Hallo,
seit dem Update auf Version 5.5.0 wird nach Quick Click mit Rechtsklick die Sprachauswahl immer angezeigt, unabhängig davon ob "Rechtsklick für mehr Optionen aktivieren" gewählt wurde oder nicht. Laut Tooltip sollten mit der Option bei Rechtsklick aber die Übersetzung statt des Kontextmenüs gezeigt werden.

Firefox Version 85.0 (64-Bit)
Windows 10

**Comment by Lusito** [comment]
Thanks for the report!
Fixed in 5.5.1

**Comment by Lusito** [comment]
Correction: fixed in 5.5.2
