### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by JVariance** [Lusito/dict.cc-translation#55]
Hi,
can you add a dark mode?
'prefers-color-scheme: dark' would suffice.

**Comment by Lusito** [comment]
Added a mediocre dark mode with version 5.6.0 (currently in review). Feel free to improve the css in a PR.

**Comment by CennoxX** [comment]
Is there a option to disable dark mode?

**Comment by Lusito** [comment]
Currently not. Dark mode is enabled automatically if you use a dark theme for your OS.
Does it not fit your dark theme or is it harder to read?
I guess I could make an option for that if that is really wanted. I'd just like to confirm, that it's not another problem first.

**Comment by CennoxX** [comment]
On dark websites it looks better than before, but on bright websites the contrast is a little bit extreme. Maybe a little bit lighter color would help, but I don't know for sure...
One thing I noticed, is that on dark websites the shadow on the website and the border around the micropanel are lighter than the rest, I don't know if that is desired...
![grafik](https://user-images.githubusercontent.com/6975881/129489271-48f53bae-245d-4573-8fc1-5ddf0d65caa3.png)

**Comment by JVariance** [comment]
> 
> 
> Currently not. Dark mode is enabled automatically if you use a dark theme for your OS.
> Does it not fit your dark theme or is it harder to read?
> I guess I could make an option for that if that is really wanted. I'd just like to confirm, that it's not another problem first.

Maybe a typical 'Theme -> Light, Dark, System' select menu and set a class or an attribute 'theme' on html or body tag accordingly.

**Comment by Lusito** [comment]
The next version will have an option to choose. Currently in review
