### ISSUE TITLE
Translations in wrong order, popularity count missing

### ISSUE THREAD

**Issue by navid-zamani** [Lusito/dict.cc-translation#58]
When I use the site directly, “überwunden” is the first result for “overcome”, as they are sorted by the very important popularity count, which gives you a hint which translation might be the most common choice.
But via the add-on, it’s “bewältigt” (apparently the results are sorted alphabetically here).

That makes the add-on misleading and hence not very useful.

It’s an unfortunate bug that spoiled an otherwise acceptable add-on. _(That probably would be great if everyone of the psychopaths who ever did anything on Chrome had died in a fire as they deserved before ruining the web and turning Mozilla so insane they adopted Chrome “webextensions”.)_

**Comment by CennoxX** [comment]
I assume you use the `Popup (pocket version)` to display your results? In the addon settings you can change what source to use, only the pocket version displays "bewältigt" first. the addon uses the official site pocket.dict.de and doesn't sort the results itself.
if you use `Popup (all details)`, `New tab (regular Dict.cc)` or `Micro panel` then "überwunden" is displayed first:
![grafik](https://user-images.githubusercontent.com/6975881/148555510-8190776f-3fdf-4a0c-b06d-733c44d3e987.png)

**Comment by navid-zamani** [comment]
No, actually, I used the icon in the toolbar, via the keyboard shortcut.  
Upon further investigation, there seems to be no tab in the settings for that one. Only for the context menu and “quick click” thing.  
So this bug would probably have to be changed to that, as your point is otherwise of course correct, and then the original problem would not be a bug.

(Btw, “quick click” is really hard to discover. It was quite hard to find out what it is and what it does. Luckily, since it conflicts with normal usage more than I’d need it, I could just disable it.)

**Comment by navid-zamani** [comment]
I’ll close this and create a new issue for it, to keep this clean
