### ISSUE TITLE
distorted micropanel on specific site

### ISSUE THREAD

**Issue by CennoxX** [Lusito/dict.cc-translation#61]
On nbcnews.com I get a distorted micropanel, where I can't read the translation:
![grafik](https://user-images.githubusercontent.com/6975881/159092826-176bfa5f-c612-4b48-b1b4-c86baa90d99e.png)
This example is from https://www.nbcnews.com/news/us-news/pete-davidson-no-longer-going-blue-origin-spaceflight-rcna20564, but it seems, it is the whole page.

**Comment by Lusito** [comment]
Thanks for the report, I'm working on a fix.

**Comment by Lusito** [comment]
Should be fixed in the next version. Currently in review.

**Comment by CennoxX** [comment]
Yes, it's fixed for me.
![grafik](https://user-images.githubusercontent.com/6975881/159241947-ca535f31-ed89-4395-9738-445e1a2ea42d.png)
Thank you for creating and maintaining this great extension!
